services:
  easylish:
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - VECTOR_BACKEND=direct
      - TEI_URL=http://tei:80
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=subtitles
      - VECTOR_DIM=384
      - QDRANT_DISTANCE=Cosine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    platform: linux/amd64
    environment:
      - MODEL_ID=${TEI_MODEL_ID:-/data/models/multilingual-e5-small}
      - RUST_LOG=info
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ../data/tei:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ../data/qdrant:/qdrant/storage
    restart: unless-stopped

  # vector-api removed; web calls TEI/Qdrant directly
