services:
  easylish:
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - VECTOR_BACKEND=remote
      - VECTOR_API_URL=http://vector-api:8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    platform: linux/amd64
    environment:
      - MODEL_ID=${TEI_MODEL_ID:-/data/models/multilingual-e5-small}
      - RUST_LOG=info
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ../data/tei:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ../data/qdrant:/qdrant/storage
    restart: unless-stopped

  vector-api:
    build:
      context: ../services/vector-api
    environment:
      - TEI_URL=http://tei:80
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=subtitles
      - VECTOR_DIM=384
      - QDRANT_DISTANCE=Cosine
      - TEI_BATCH=32
      - SUBTITLES_DIR=/data/subtitles
    ports:
      - "8000:8000"
    depends_on:
      - tei
      - qdrant
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
    volumes:
      - ../data/subtitles:/data/subtitles:ro
