[project]
name = "vector-api"
version = "0.2.0"
description = "Vector microservice wrapping TEI + Qdrant"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.111",
  "uvicorn[standard]>=0.30",
  "httpx>=0.27",
  "qdrant-client>=1.10",
  "pydantic>=2.7",
]

